### ISSUE TITLE
Integration in Lichess

### ISSUE THREAD

**Issue by ghost** [SimonLammer/lichess-accept-random-challenge#5]
Hallo @SimonLammer ,
Was muss ich, nachdem ich es installiert habe noch machen? Woher nimmt er denn den Player Pool ? 
Ich habe dein Plugin installiert. Kann man das auch auf YT nutzen, da ich kein Twitch habe? 

Gruß @Zeyecx

**Comment by SimonLammer** [comment]
Ich bin nicht ganz sicher deine Frage richtig verstanden zu haben. Das Plugin sucht aus allen aktiven Herausforderungen an dich eine per Zufall aus und akzeptiert diese. Das hat weder mit Twitch noch YouTube etwas zu tun.

---

Hi, I'm not sure I understood your question correctly. The plugin accepts one of the active challenges against you randomly. This doesn't have anything to do with Twitch or YouTube.
